In [2]:
import pandas as pd
import numpy as np
import googlemaps
from datetime import datetime

In [3]:
df = pd.read_csv('RideSharingData/yellow_tripdata_2016-01.csv')

In [4]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RatecodeID,store_and_fwd_flag,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
0,2,2016-01-01 00:00:00,2016-01-01 00:00:00,2,1.10,-73.990372,40.734695,1,N,-73.981842,40.732407,2,7.5,0.5,0.5,0.00,0.00,0.3,8.80
1,2,2016-01-01 00:00:00,2016-01-01 00:00:00,5,4.90,-73.980782,40.729912,1,N,-73.944473,40.716679,1,18.0,0.5,0.5,0.00,0.00,0.3,19.30
2,2,2016-01-01 00:00:00,2016-01-01 00:00:00,1,10.54,-73.984550,40.679565,1,N,-73.950272,40.788925,1,33.0,0.5,0.5,0.00,0.00,0.3,34.30
3,2,2016-01-01 00:00:00,2016-01-01 00:00:00,1,4.75,-73.993469,40.718990,1,N,-73.962242,40.657333,2,16.5,0.0,0.5,0.00,0.00,0.3,17.30
4,2,2016-01-01 00:00:00,2016-01-01 00:00:00,3,1.76,-73.960625,40.781330,1,N,-73.977264,40.758514,2,8.0,0.0,0.5,0.00,0.00,0.3,8.80
5,2,2016-01-01 00:00:00,2016-01-01 00:18:30,2,5.52,-73.980118,40.743050,1,N,-73.913490,40.763142,2,19.0,0.5,0.5,0.00,0.00,0.3,20.30
6,2,2016-01-01 00:00:00,2016-01-01 00:26:45,2,7.45,-73.994057,40.719990,1,N,-73.966362,40.789871,2,26.0,0.5,0.5,0.00,0.00,0.3,27.30
7,1,2016-01-01 00:00:01,2016-01-01 00:11:55,1,1.20,-73.979424,40.744614,1,N,-73.992035,40.753944,2,9.0,0.5,0.5,0.00,0.00,0.3,10.30
8,1,2016-01-01 00:00:02,2016-01-01 00:11:14,1,6.00,-73.947151,40.791046,1,N,-73.920769,40.865578,2,18.0,0.5,0.5,0.00,0.00,0.3,19.30
9,2,2016-01-01 00:00:02,2016-01-01 00:11:08,1,3.21,-73.998344,40.723896,1,N,-73.995850,40.688400,2,11.5,0.5,0.5,0.00,0.00,0.3,12.80
10,2,2016-01-01 00:00:03,2016-01-01 00:06:19,1,0.79,-74.006149,40.744919,1,N,-73.993797,40.741440,2,6.0,0.5,0.5,0.00,0.00,0.3,7.30
11,2,2016-01-01 00:00:03,2016-01-01 00:15:49,6,2.43,-73.969330,40.763538,1,N,-73.995689,40.744251,1,12.0,0.5,0.5,3.99,0.00,0.3,17.29
12,2,2016-01-01 00:00:03,2016-01-01 00:00:11,4,0.01,-73.989021,40.721539,1,N,-73.988960,40.721699,2,2.5,0.5,0.5,0.00,0.00,0.3,3.80
13,1,2016-01-01 00:00:04,2016-01-01 00:14:32,1,3.70,-74.004303,40.742241,1,N,-74.007362,40.706936,1,14.0,0.5,0.5,3.05,0.00,0.3,18.35
14,1,2016-01-01 00:00:05,2016-01-01 00:14:27,2,2.20,-73.991997,40.718578,1,N,-74.005135,40.739944,1,11.0,0.5,0.5,1.50,0.00,0.3,13.80
15,2,2016-01-01 00:00:05,2016-01-01 00:07:17,1,0.54,-73.985161,40.768951,1,N,-73.990227,40.761730,2,6.0,0.5,0.5,0.00,0.00,0.3,7.30
16,2,2016-01-01 00:00:05,2016-01-01 00:07:14,1,1.92,-73.973091,40.795361,1,N,-73.978371,40.773151,2,7.5,0.5,0.5,0.00,0.00,0.3,8.80
17,1,2016-01-01 00:00:06,2016-01-01 00:04:44,1,1.70,-73.982101,40.774696,1,Y,-73.970940,40.796707,1,7.0,0.5,0.5,1.65,0.00,0.3,9.95
18,2,2016-01-01 00:00:06,2016-01-01 00:07:14,1,1.38,-73.994843,40.718498,1,N,-73.989807,40.734230,1,7.0,0.5,0.5,1.66,0.00,0.3,9.96
19,1,2016-01-01 00:00:07,2016-01-01 00:20:35,2,4.90,-73.953033,40.672115,1,N,-73.986572,40.710594,1,19.0,0.5,0.5,4.06,0.00,0.3,24.36
20,1,2016-01-01 00:00:07,2016-01-01 00:09:49,1,1.80,-73.989166,40.726589,1,N,-74.009483,40.715073,2,9.0,0.5,0.5,0.00,0.00,0.3,10.30
21,2,2016-01-01 00:00:08,2016-01-01 00:18:51,1,3.09,-73.999069,40.720173,1,N,-73.973389,40.756561,2,14.5,0.5,0.5,0.00,0.00,0.3,15.80
22,2,2016-01-01 00:00:08,2016-01-01 00:04:37,1,0.72,-73.997139,40.747219,1,N,-74.004486,40.751797,2,5.0,0.5,0.5,0.00,0.00,0.3,6.30
23,2,2016-01-01 00:00:08,2016-01-01 00:03:24,1,0.69,-73.997414,40.736675,1,N,-73.985664,40.732681,2,4.5,0.5,0.5,0.00,0.00,0.3,5.80
24,1,2016-01-01 00:00:09,2016-01-01 00:19:03,3,5.30,-73.997131,40.736961,1,N,-73.928421,40.755581,1,18.0,0.5,0.5,3.85,0.00,0.3,23.15
25,1,2016-01-01 00:00:09,2016-01-01 00:07:18,2,1.20,-73.963913,40.712173,1,N,-73.951332,40.712200,2,7.0,0.5,0.5,0.00,0.00,0.3,8.30
26,2,2016-01-01 00:00:10,2016-01-01 00:06:15,2,0.97,-73.999397,40.743900,1,N,-73.988876,40.745319,2,6.0,0.5,0.5,0.00,0.00,0.3,7.30
27,2,2016-01-01 00:00:10,2016-01-01 00:02:20,1,0.87,-73.954407,40.778069,1,N,-73.948929,40.788582,2,4.5,0.5,0.5,0.00,0.00,0.3,5.80
28,2,2016-01-01 00:00:12,2016-01-01 00:01:17,1,0.13,-73.991653,40.754559,1,N,-73.990601,40.756119,2,3.0,0.5,0.5,0.00,0.00,0.3,4.30
29,1,2016-01-01 00:00:14,2016-01-01 00:13:02,1,2.40,-73.995598,40.744240,1,N,-73.985458,40.768711,1,11.0,0.5,0.5,3.05,0.00,0.3,15.35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10906828,2,2016-01-30 23:06:50,2016-01-30 23:29:24,1,3.79,-73.962677,40.758549,1,N,-73.976273,40.790939,1,17.0,0.5,0.5,3.00,0.00,0.3,21.30
10906829,2,2016-01-30 23:34:47,2016-01-31 00:06:10,2,13.94,-73.976387,40.785782,1,N,-73.850601,40.723969,1,40.0,0.5,0.5,9.37,5.54,0.3,56.21
10906830,2,2016-01-31 01:45:36,2016-01-31 01:52:42,1,1.36,-73.987373,40.764118,1,N,-73.987106,40.749790,1,7.0,0.5,0.5,1.66,0.00,0.3,9.96
10906831,2,2016-01-31 02:01:55,2016-01-31 02:15:06,1,4.64,-73.985352,40.746632,1,N,-74.006317,40.708248,1,16.0,0.5,0.5,2.00,0.00,0.3,19.30
10906832,2,2016-01-31 02:31:44,2016-01-31 02:45:49,1,2.97,-74.004097,40.720020,1,N,-73.962097,40.713169,1,12.5,0.5,0.5,2.76,0.00,0.3,16.56
10906833,2,2016-01-31 02:57:08,2016-01-31 03:04:54,2,0.97,-73.985603,40.718128,1,N,-73.988441,40.727879,1,6.5,0.5,0.5,1.20,0.00,0.3,9.00
10906834,2,2016-01-31 03:06:45,2016-01-31 03:10:11,1,0.60,-73.985901,40.726799,1,N,-73.987038,40.729359,2,4.5,0.5,0.5,0.00,0.00,0.3,5.80
10906835,2,2016-01-31 03:24:39,2016-01-31 03:43:26,1,5.44,-74.003418,40.738838,1,N,-73.964050,40.805660,1,18.0,0.5,0.5,2.50,0.00,0.3,21.80
10906836,2,2016-01-31 03:52:15,2016-01-31 03:59:42,1,2.25,-73.976257,40.786018,1,N,-73.952789,40.808102,1,8.5,0.5,0.5,1.96,0.00,0.3,11.76
10906837,2,2016-01-31 04:00:58,2016-01-31 04:14:43,1,5.55,-73.952606,40.808289,1,N,-73.998894,40.760441,1,18.0,0.5,0.5,5.79,0.00,0.3,25.09
10906838,2,2016-01-31 04:16:39,2016-01-31 04:24:45,1,1.48,-73.996300,40.759861,1,N,-73.981102,40.763569,2,7.5,0.5,0.5,0.00,0.00,0.3,8.80
10906839,2,2016-01-31 04:30:54,2016-01-31 04:38:21,1,2.27,-73.982803,40.762531,1,N,-74.002571,40.734211,1,8.5,0.5,0.5,1.00,0.00,0.3,10.80
10906840,2,2016-01-31 04:46:04,2016-01-31 04:50:13,1,1.13,-74.001663,40.740952,1,N,-73.992531,40.748619,2,5.5,0.5,0.5,0.00,0.00,0.3,6.80
10906841,2,2016-01-31 05:11:55,2016-01-31 05:19:04,1,1.54,-74.003029,40.749641,1,N,-73.980408,40.744518,1,7.5,0.5,0.5,1.76,0.00,0.3,10.56
10906842,2,2016-01-31 19:09:53,2016-01-31 19:24:59,1,2.73,-73.939568,40.794399,1,N,-73.937172,40.824169,2,12.5,1.0,0.5,0.00,0.00,0.3,14.30
10906843,2,2016-01-31 19:27:37,2016-01-31 19:33:33,1,1.38,-73.938293,40.822929,1,N,-73.939636,40.807831,1,7.0,1.0,0.5,1.76,0.00,0.3,10.56
10906844,2,2016-01-31 19:38:24,2016-01-31 19:54:59,1,4.74,-73.936470,40.798901,1,N,-73.988098,40.763248,1,16.5,1.0,0.5,3.66,0.00,0.3,21.96
10906845,2,2016-01-31 19:55:54,2016-01-31 20:01:58,1,1.14,-73.986931,40.762642,1,N,-73.999153,40.754929,2,6.0,0.5,0.5,0.00,0.00,0.3,7.30
10906846,2,2016-01-31 20:14:22,2016-01-31 20:24:16,1,3.01,-74.005981,40.751209,1,N,-73.976608,40.785400,1,11.0,0.5,0.5,2.46,0.00,0.3,14.76
10906847,2,2016-01-31 20:36:58,2016-01-31 20:41:40,1,0.97,-73.977661,40.784191,1,N,-73.972931,40.795769,1,5.5,0.5,0.5,1.00,0.00,0.3,7.80
10906848,2,2016-01-31 20:53:56,2016-01-31 21:05:13,1,2.84,-73.976212,40.786301,1,N,-73.977837,40.756989,1,11.5,0.5,0.5,1.50,0.00,0.3,14.30
10906849,2,2016-01-31 21:28:59,2016-01-31 22:01:58,1,7.83,-74.002953,40.750481,1,N,-73.958153,40.656689,1,29.0,0.5,0.5,5.00,0.00,0.3,35.30
10906850,2,2016-01-31 22:36:41,2016-01-31 22:45:04,1,2.50,-74.009277,40.717049,1,N,-73.994637,40.750488,1,9.5,0.5,0.5,2.16,0.00,0.3,12.96
10906851,2,2016-01-31 22:53:00,2016-01-31 22:59:37,1,1.68,-74.003578,40.750751,1,N,-74.002159,40.734909,1,7.0,0.5,0.5,1.00,0.00,0.3,9.30
10906852,2,2016-01-31 23:00:11,2016-01-31 23:12:08,1,2.65,-74.002159,40.734852,1,N,-73.999680,40.761669,1,11.0,0.5,0.5,1.00,0.00,0.3,13.30
10906853,2,2016-01-31 23:30:32,2016-01-31 23:38:18,1,2.20,-74.003578,40.751011,1,N,-73.982651,40.767509,2,8.5,0.5,0.5,0.00,0.00,0.3,9.80
10906854,1,2016-01-05 00:15:55,2016-01-05 00:16:06,1,0.00,-73.945488,40.751530,1,N,-73.945457,40.751530,2,2.5,0.5,0.5,0.00,0.00,0.3,3.80
10906855,1,2016-01-05 06:12:46,2016-03-19 20:45:50,3,1.40,-73.994240,40.766586,1,N,-73.984428,40.753922,2,7.5,0.5,0.5,0.00,0.00,0.3,8.80
10906856,1,2016-01-05 06:21:44,2016-03-28 12:54:26,1,2.10,-73.948067,40.776531,1,N,-73.978188,40.777435,1,11.5,0.0,0.5,2.45,0.00,0.3,14.75
10906857,1,2016-01-05 06:15:21,2016-01-05 06:15:36,3,0.00,-73.960938,40.758595,2,N,-73.961006,40.758583,2,52.0,0.0,0.5,0.00,5.54,0.3,58.34

In [5]:
df.head(5)

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,pickup_longitude,pickup_latitude,RatecodeID,store_and_fwd_flag,dropoff_longitude,dropoff_latitude,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
0,2,2016-01-01 00:00:00,2016-01-01 00:00:00,2,1.10,-73.990372,40.734695,1,N,-73.981842,40.732407,2,7.5,0.5,0.5,0.0,0.0,0.3,8.8
1,2,2016-01-01 00:00:00,2016-01-01 00:00:00,5,4.90,-73.980782,40.729912,1,N,-73.944473,40.716679,1,18.0,0.5,0.5,0.0,0.0,0.3,19.3
2,2,2016-01-01 00:00:00,2016-01-01 00:00:00,1,10.54,-73.984550,40.679565,1,N,-73.950272,40.788925,1,33.0,0.5,0.5,0.0,0.0,0.3,34.3
3,2,2016-01-01 00:00:00,2016-01-01 00:00:00,1,4.75,-73.993469,40.718990,1,N,-73.962242,40.657333,2,16.5,0.0,0.5,0.0,0.0,0.3,17.3
4,2,2016-01-01 00:00:00,2016-01-01 00:00:00,3,1.76,-73.960625,40.781330,1,N,-73.977264,40.758514,2,8.0,0.0,0.5,0.0,0.0,0.3,8.8

In [57]:
class Request:

    def __init__(self, req_id, no_of_passengers, will_to_walk, 
                 dest_id,req_time, max_delay):
        
        self.req_id = req_id
        self.no_of_passengers = no_of_passengers
        self.will_to_walk = will_to_walk
        #self.origin_lon = origin_lon
        #self.origin_lat = origin_lat
        self.dest_id = dest_id
        #self.dest_lon = dest_lon
        #self.dest_lat = dest_lat
        self.req_time = req_time
        self.max_delay = max_delay

In [58]:
def fetch_long_lat_for_dest_id(dest_id):

    #TODO
    #long_lat 52.2296756, 21.0122287 , 52.406374, 16.9251681
    long = 51.234567
    lat = 15.567456
    return long, lat

In [59]:
class Destination:
    
    def __init__(self, dest_id):
                
        long, lat = fetch_long_lat_for_dest_id(dest_id)
        self.dest_id = dest_id
        self.long = long
        self.lat = lat
        #self.dist_from_src = dist_from_src
        #self.time_to_reach = time_to_reach
    
    

    
    def calculate_dist_from_src(self):
        src_long = 44.406374
        src_lat = 20.406374
        dist_from_src = geopy.distance.vincenty((src_long, src_lat), (self.long, self.lat)).km
        return dist_from_src 
    
    def calculate_time_to_reach():
        #TODO
        return 0

In [60]:
dest1 = Destination(1)
dest2 = Destination(2)

dest1.calculate_dist_from_src()

C:\Users\mayur\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: DeprecationWarning: Vincenty is deprecated and is going to be removed in geopy 2.0. Use `geopy.distance.geodesic` (or the default `geopy.distance.distance`) instead, which is more accurate and always converges.

840.7888131292325

In [61]:
class ReqRideAllotment:
    
    def __init__(self, req_id, ride_id, shr_time, shr_dist, shr_cost):
        
        self.req_id = req_id
        self.ride_id = ride_id
        self.shr_time = shr_time
        self.shr_dist = shr_dist
        self.shr_cost = shr_cost

In [62]:
# Instantiate the RideRequest object for now
reqA = Request(1, 1, 'Y', 1, 10, 10)
reqB = Request(2, 2, 'Y', 2, 10, 10)


all_req_t_slot_1 = [reqA, reqB]
all_req_t_slot_1

In [65]:
def sharability_graph(all_req_t_slot_1):
    
    taxi_capacity = 3
    for reqA in all_req_t_slot_1:
        for reqB in all_req_t_slot_1:
            if reqA != reqB and reqA.no_of_passengers + reqB.no_of_passengers <= taxi_capacity:

                reqA_orgin_dest_dist = Destination(reqA.dest_id).calculate_dist_from_src()
                reqB_orgin_dest_dist = Destination(reqB.dest_id).calculate_dist_from_src()
                
                #print('reqA_orgin_dest_dist: ',reqA_orgin_dest_dist)
                #print('reqB_orgin_dest_dist: ',reqB_orgin_dest_dist)

In [66]:
sharability_graph(all_req_t_slot_1)

C:\Users\mayur\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: DeprecationWarning: Vincenty is deprecated and is going to be removed in geopy 2.0. Use `geopy.distance.geodesic` (or the default `geopy.distance.distance`) instead, which is more accurate and always converges.

In [1]:
import geopy.distance

coords_1 = (52.2296756, 21.0122287)
coords_2 = (52.406374, 16.9251681)

print(geopy.distance.vincenty(coords_1, coords_2).km)

279.35290160386563

C:\Users\mayur\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: Vincenty is deprecated and is going to be removed in geopy 2.0. Use `geopy.distance.geodesic` (or the default `geopy.distance.distance`) instead, which is more accurate and always converges.

In [ ]:
#gmaps = googlemaps.Client(key = )